name: stripe
version: 4.11.0
description: A simple Stripe API wrapper, that is meant to be used on the server.
homepage: https://github.com/enyo/stripe-dart
documentation: https://github.com/enyo/stripe-dart/blob/main/README.md
environment:
  sdk: ^3.0.0
dependencies:
  crypto: ^3.0.3
  http: ^0.13.6
  json_annotation: ^4.9.0
  meta: ^1.15.0
  logging: ^1.2.0
  dio: ^5.4.3
dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  test: ^1.25.5
  mocktail: ^1.0.3
  lints: ^3.0.0
