name: stripe
version: 3.0.0
description: Stripe API wrapper
homepage: https://gitlab.com/exitlive/stripe-dart
documentation: https://gitlab.com/exitlive/stripe-dart/blob/master/README.md
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  crypto: ^3.0.0
  http: ^0.13.1
  json_annotation: ^4.0.1
  meta: ^1.1.7
  logging: ^1.0.1
dev_dependencies:
  grinder: ^0.9.0
  pedantic: ">=1.11.0"
  json_serializable: ^4.1.0
  build_runner: ^1.0.0
  test: ^1.3.0
